permalink: /:title/
gems:
  - jekyll-sitemap

title: Sebbas.org
url: http://sebbas.org
baseurl: ""
description: "Sebastián is a programmer, Blender developer, computer graphics researcher, Android developer, swimmer, pull-up lover and sometimes just likes to read."
author: Sebastián
twitter: realsebbas
stackoverflow: 1480784/sebbas
trello: sebbas
googleplay: sebbas
vimeo: sebbas
linkedin: 
bitbucket: sebbas
goodreads: sebbas
delicious: sebbas
hackernews: sebbas
instagram: realsebbas
medium: sebbas
youtube: UCiU3oTGKL4GDr5xgK_EMjnQ
500px: sebbas
irc: sebbas
username: sebbas
email: sebbas@sebbas.org

timezone: Europe/Madrid
google_analytics_tracking_id: UA-39520634-1
